name: Generate Snake Game

on:
  schedule:
    # Runs daily at 12 AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from Contribution Grid
        uses: Platane/snk@v2
        with:
          github_user_name: YOUR_GITHUB_USERNAME
          outputs: dist/snake.svg

      - name: Push Snake Animation to the repository
        run: |
          mkdir -p output
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generate Snake Animation"
          git push
